name: Python CI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to your requirements file if you have one

    - name: Run tests
      run: |
        python test.py  # Change this to your test script name if you have one

    - name: Build application
      run: |
        python build.py  # Change this to your build script name if you have one
